/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Form;

import java.awt.Color;
import java.awt.HeadlessException;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JOptionPane;

/**
 *
 * @author anton
 */
public class Form_Formulario_Empresas extends javax.swing.JPanel {

    private final Integer empresaId; // null para nueva empresa, int para edición
    private final boolean modoEdicion;
    private java.util.function.Consumer<javax.swing.JComponent> navigator;

    // Constructor para NUEVA empresa
    public Form_Formulario_Empresas() {
        this.empresaId = null;
        this.modoEdicion = false;
        initComponents();
        configurarModo();
    }

    // Constructor para EDITAR empresa
    public Form_Formulario_Empresas(int empresaId) {
        this.empresaId = empresaId;
        this.modoEdicion = true;
        initComponents();
        configurarModo();
        cargarDatosEmpresa();
    }

    private void configurarModo() {
        if (modoEdicion) {
            jLabel1.setText("Editar Empresa"); // Cambiar título
            lblGuardar.setText("Actualizar");   // Cambiar texto del botón
        } else {
            jLabel1.setText("Nueva Empresa");   // Título por defecto
            lblGuardar.setText("Guardar");      // Texto por defecto
        }
    }

    private void cargarDatosEmpresa() {
        if (empresaId != null) {
            Map<String, Object> datos = Modelo.Model_Empresas.obtenerEmpresaPorId(empresaId);
            if (datos != null) {
                nombreEmpresaTxt.setText((String) datos.get("nombre"));
                nombreResponsableTxt.setText((String) datos.get("nombre_responsable"));
                telResponsableTxt.setText((String) datos.get("telefono_responsable"));
                eMailResponsableTxt.setText((String) datos.get("correo_responsable"));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new Swing.PanelBorder();
        lblNombreEmpresa = new javax.swing.JLabel();
        nombreEmpresaTxt = new javax.swing.JTextField();
        lblNombreResponsable = new javax.swing.JLabel();
        nombreResponsableTxt = new javax.swing.JTextField();
        lblTelResponsable = new javax.swing.JLabel();
        telResponsableTxt = new javax.swing.JTextField();
        lblEmailResponsable = new javax.swing.JLabel();
        eMailResponsableTxt = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JPanel();
        lblcancelar = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        lblGuardar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreEmpresa.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblNombreEmpresa.setText("Nombre de la empresa:");

        nombreEmpresaTxt.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        nombreEmpresaTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 255)));

        lblNombreResponsable.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblNombreResponsable.setText("Nombre del responsable:");

        nombreResponsableTxt.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        nombreResponsableTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 255)));

        lblTelResponsable.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblTelResponsable.setText("Telefono del responsable:");

        telResponsableTxt.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        telResponsableTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 255)));
        telResponsableTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telResponsableTxtKeyTyped(evt);
            }
        });

        lblEmailResponsable.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblEmailResponsable.setText("Correo electronico:");

        eMailResponsableTxt.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        eMailResponsableTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 255)));

        btnCancelar.setBackground(new java.awt.Color(30, 103, 201));

        lblcancelar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblcancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblcancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcancelar.setText("Cancelar");
        lblcancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcancelarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblcancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        btnGuardar.setBackground(new java.awt.Color(30, 103, 201));

        lblGuardar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(255, 255, 255));
        lblGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuardar.setText("Guardar");
        lblGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(22, 94, 183));
        jLabel1.setText("Nueva empresa");

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(lblNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(lblNombreResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(nombreEmpresaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(nombreResponsableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(lblTelResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblEmailResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(telResponsableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(eMailResponsableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(235, 235, 235))
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEmpresa)
                    .addComponent(lblNombreResponsable))
                .addGap(8, 8, 8)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreEmpresaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreResponsableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelResponsable)
                    .addComponent(lblEmailResponsable))
                .addGap(8, 8, 8)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telResponsableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eMailResponsableTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcancelarMouseClicked
        if (navigator != null) {
            Form_Empresas back = new Form_Empresas();
            back.setNavigator(navigator);
            navigator.accept(back);     // volver a la lista
        }
    }//GEN-LAST:event_lblcancelarMouseClicked

    private void lblcancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcancelarMouseEntered
        btnCancelar.setBackground(new Color(80, 158, 255));
    }//GEN-LAST:event_lblcancelarMouseEntered

    private void lblcancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcancelarMouseExited
        btnCancelar.setBackground(new Color(30, 103, 201));
    }//GEN-LAST:event_lblcancelarMouseExited

    private void lblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseClicked
        if (navigator != null) {
            guardar();
            Form_Empresas back = new Form_Empresas();
            back.setNavigator(navigator);
            navigator.accept(back);     // volver a la lista tras guardar
        }
    }//GEN-LAST:event_lblGuardarMouseClicked

    private void lblGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseEntered
        btnGuardar.setBackground(new Color(80, 158, 255));
    }//GEN-LAST:event_lblGuardarMouseEntered

    private void lblGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseExited
        btnGuardar.setBackground(new Color(30, 103, 201));
    }//GEN-LAST:event_lblGuardarMouseExited

    private void telResponsableTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telResponsableTxtKeyTyped
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros && telResponsableTxt.getText().length() >= 10) {
            evt.consume();
        }
        if (telResponsableTxt.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_telResponsableTxtKeyTyped

    public void setNavigator(java.util.function.Consumer<javax.swing.JComponent> nav) {
        this.navigator = nav;
    }

    private void guardar() {
        try {
            Map<String, Object> datos = new HashMap<>();
            // ✅ USAR NOMBRES CORRECTOS SEGÚN LA BASE DE DATOS
            datos.put("nombre", nombreEmpresaTxt.getText());
            datos.put("nombre_responsable", nombreResponsableTxt.getText());
            datos.put("telefono_responsable", telResponsableTxt.getText());
            datos.put("correo_responsable", eMailResponsableTxt.getText());
            datos.put("direccion", ""); // Agregar campo dirección vacío

            boolean exito;
            if (modoEdicion && empresaId != null) {
                // MODO EDICIÓN - usar actualizarEmpresa
                exito = Modelo.Model_Empresas.actualizarEmpresa(empresaId, datos);
            } else {
                // MODO CREACIÓN - usar guardarEmpresa
                exito = Modelo.Model_Empresas.guardarEmpresa(datos);
            }

            if (exito) {
                String mensaje = modoEdicion ? "Empresa actualizada con éxito" : "Empresa guardada con éxito";
                JOptionPane.showMessageDialog(null, mensaje);
            } else {
                JOptionPane.showMessageDialog(null, "Error al guardar");
            }
        } catch (HeadlessException e) {
            System.err.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Error al guardar");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JTextField eMailResponsableTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmailResponsable;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblNombreEmpresa;
    private javax.swing.JLabel lblNombreResponsable;
    private javax.swing.JLabel lblTelResponsable;
    private javax.swing.JLabel lblcancelar;
    private javax.swing.JTextField nombreEmpresaTxt;
    private javax.swing.JTextField nombreResponsableTxt;
    private Swing.PanelBorder panelBorder1;
    private javax.swing.JTextField telResponsableTxt;
    // End of variables declaration//GEN-END:variables
}